### PR TITLE
Bounegta assignment p2

### PR DESCRIPTION
**Pull request by KenzoBou**

### CODE REVIEW

**Comment by mathurinm** [comment]
@KenzoBou just remove the 2 files you committed that should not be there and you're done

**Comment by mathurinm** [comment]
you can just go back to your previous branch and undo the last commit. it's a cleaner way to proceed

**Comment by KenzoBou** [comment]
That should be done. Thanks a lot

De : mathurinm ***@***.***>
Date : mardi, 8 novembre 2022 à 18:05
À : mathurinm/github-assignment ***@***.***>
Cc : Kenzo BOUNEGTA ***@***.***>, Mention ***@***.***>
Objet : Re: [mathurinm/github-assignment] Bounegta assignment p2 (PR #120)

you can just go back to your previous branch and undo the last commit. it's a cleaner way to proceed

**Comment by mathurinm** [comment]
:+1:

**Pull request closed without merging**
