### PR TITLE
Added X to MML

### PR DESCRIPTION
**Pull request by tagada5-9**

### CODE REVIEW

**Comment by mathurinm** [comment]
You have a conflict @tagada5-9, you need to fix it before I can merge

**Comment by mathurinm** [comment]
there is still a conflict

**Comment by tagada5-9** [comment]
Is there still a conflict or can it be merged ?

**Comment by tagada5-9** [comment]
Is it a problem that my changes not only include the text file but also numpy and sklearn files ?
Best regards,
Matthieu

**Comment by mathurinm** [comment]
Yes, it should not be the case

**Comment by mathurinm** [comment]
You need to do 2 separate PRs. Can you check the instructions in the Readme ?

**Pull request closed without merging**
