### PR TITLE
Han wang

### PR DESCRIPTION
**Pull request by Hanhan2024hec**
Han_Wang  Lab4

### CODE REVIEW

**Comment by mathurinm** [comment]
You have a conflict, check the readme on how to fix it. **Do not** start a new PR, conitnue working on this one

**Comment by mathurinm** [comment]
@Hanhan2024hec you're doing the 2 parts simultaneously, in the first part you should send a PR that only modifies the students.txt file. please read the readme carefully

**Comment by mathurinm** [comment]
Ok now the tests run, it reamins to make the CI happy

**Comment by Hanhan2024hec** [comment]
Hi professor, I adjust my code and make CI happy :), you can check it now

**Comment by mathurinm** [comment]
:+1:

**Pull request closed without merging**
