### PR TITLE
Abdufattokh_ASHUROV

### PR DESCRIPTION
**Pull request by FredericAnnou**

### CODE REVIEW

**Comment by mathurinm** [comment]
can you edit the name of the PR? why that name for the branch?

**Comment by FredericAnnou** [comment]
The name of this PR is "Abdufattokh_ASHUROV", which is my name and my surname.  The task says "The name of the PR should contain your first and last names." Isn't the PR named right then?

**Comment by mathurinm** [comment]
Sorry, I got confused because your username is FredericAnnou. Same person?

**Comment by FredericAnnou** [comment]
Yes, I'm also sorry about this. It's just the pseudonym that I came up with for online services.

**Comment by mathurinm** [comment]
No problem at all! Good job for the PR :+1:

**Pull request closed without merging**
